//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./UGEN.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace UGENGenerated {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="UGENParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IUGENVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="UGENParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] UGENParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UGENParser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPattern([NotNull] UGENParser.PatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UGENParser.patternExprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPatternExprList([NotNull] UGENParser.PatternExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UGENParser.patternExprOperatorPipe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPatternExprOperatorPipe([NotNull] UGENParser.PatternExprOperatorPipeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UGENParser.patternExprOperatorOptional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPatternExprOperatorOptional([NotNull] UGENParser.PatternExprOperatorOptionalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UGENParser.patternExprTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPatternExprTerm([NotNull] UGENParser.PatternExprTermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UGENParser.optionalFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionalFlag([NotNull] UGENParser.OptionalFlagContext context);
}
} // namespace UGENGenerated
