name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Build and Publish with dotnet
      run: dotnet publish --configuration Release
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: UGEN
        path: /home/runner/work/UGEN/UGEN/UGEN/bin/Release/net5.0/publish/
