name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: dotnet publish
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: UGEN
        path: |
          Build/
          !**/*.xml
